# Using open jdk 8 image from docker hub
FROM openjdk:8

# adding Application jar and renaming it to app.jar
ADD build/libs/Grpc-Wallet-Client-0.0.1-SNAPSHOT-all.jar Grpc-Wallet-Client-0.0.1-SNAPSHOT-all.jar

#Entry point of application
CMD exec java -jar Grpc-Wallet-Client-0.0.1-SNAPSHOT-all.jar